#'PPMS data loader
#'
#'This function loads in data from a .dat file generated by a Quantum Design PPMS.
#'
#' @param folder String describing folder containing the datafile
#' @param filename String of datafile name, should end in .dat
#' @param removenames Vector of strings to filter out of column names, i.e. words to search for in column names; these columns will not be loaded. Example: removenames = c("Frequency","Amp") will not load the Frequency column nor the Amplitude column. The default is to remove columns describing instrument status and columns used to calculate observables (with the exception of the calculated straw center position). To **not** remove any columns, input an empty vector c().
#' @param preerveempty Boolean for whether to preserve columns which contain NO data.
#' @param relativetime Boolean for whether to rescale the time stamp to begin at 0 and count from there, creating a new column called 'AbsTimeSec'. Default is to instead report the PPMS measure of absolute time. To remove the old column of absolute time, add "Stamp" or similar to the vector in 'removenames'.
#' @returns Dataframe containing selected columns in the .dat file.
#'
OpenPPMSData <- function(folder=getwd(),filename=NULL,removenames=c("Drive","Fit","Center","Count","Gain","Bridge","Stat","Meas","Pressure","Min","Max","Phase","Elap","Map","Stamp","PPMS"),preserveempty=FALSE,relativetime=FALSE){
  if(is.null(filename))
    stop("Please input your filename")
  fullfilepath <- paste(folder, filename, sep = "/")
  originaldata <- read.delim(fullfilepath,
                             header = TRUE,
                             sep = ",",
                             na.strings = "",
                             stringsAsFactors = TRUE,
                             skip = 30)
  moddata <- originaldata
  names(moddata) <- gsub(x = names(moddata),
                         pattern = "\\.",
                         replacement = "")
  if(relativetime == TRUE){
    AbsTimesec<-moddata$TimeStampsec-moddata$TimeStampsec[1]
    moddata<-cbind(moddata,AbsTimesec)
  }
  if(preserveempty == FALSE){
    moddata <- Filter(function(x)!all(is.na(x)), moddata)}
  if(!is.vector(removenames)){
    return(moddata)
  }else{
    moddata <- moddata %>%
      select(-contains(removenames))
    return(moddata)
  }
}
